version: "3.5"
services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.20

  db_films:
    container_name: db_films
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.20

  db_AI:
    container_name: db_AI
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.20

  frontend:
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: node
