version: "3.8"
services:
  db_auth:
    restart: always
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB:postgres
    image: postgres:alpine3.20

  db_films:
    restart: always
    container_name: db_films
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.20

  db_AI:
    container_name: db_AI
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.20

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - WEB_PASSWORD=root
      - WEB_USER=admin
    image: node

  backendCore:
    build:
      context: ./backendCore
    container_name: backendCore
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL='postgres://admin:root@db:5432/postgres?sslmode=disable'
    depends_on:
      - db_auth
    image: golang

  backendAI:
    build:
      context: ./backendAI
    container_name: backendAI
    command: ["python", "main.py"]
    ports:
      - "5000:5000"
    environment:
      - AI_PASSWORD=root
      - AI_USER=admin
    image: python
